//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaylistManager.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTexts() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlaylistManager.App.Resources.Texts.AppTexts", typeof(AppTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Audiobook.
        /// </summary>
        internal static string AudiobookString {
            get {
                return ResourceManager.GetString("AudiobookString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Go back to selection screen.
        /// </summary>
        internal static string BackToSelectString {
            get {
                return ResourceManager.GetString("BackToSelectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Description of the new playlist.
        /// </summary>
        internal static string DefaultPlaylistDescriptionString {
            get {
                return ResourceManager.GetString("DefaultPlaylistDescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Duration.
        /// </summary>
        internal static string DurationString {
            get {
                return ResourceManager.GetString("DurationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Media Count.
        /// </summary>
        internal static string MediaCountSortString {
            get {
                return ResourceManager.GetString("MediaCountSortString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Media Count.
        /// </summary>
        internal static string MediaCountString {
            get {
                return ResourceManager.GetString("MediaCountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Search media in playlist.
        /// </summary>
        internal static string MediaSearchPlaceholderString {
            get {
                return ResourceManager.GetString("MediaSearchPlaceholderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Music.
        /// </summary>
        internal static string MusicString {
            get {
                return ResourceManager.GetString("MusicString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Name.
        /// </summary>
        internal static string NameSortString {
            get {
                return ResourceManager.GetString("NameSortString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New medium.
        /// </summary>
        internal static string NewMediumString {
            get {
                return ResourceManager.GetString("NewMediumString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New playlist.
        /// </summary>
        internal static string NewPlaylistString {
            get {
                return ResourceManager.GetString("NewPlaylistString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Playlist description.
        /// </summary>
        internal static string PlaylistDescriptionString {
            get {
                return ResourceManager.GetString("PlaylistDescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Search playlists.
        /// </summary>
        internal static string PlaylistSearchPlaceholderString {
            get {
                return ResourceManager.GetString("PlaylistSearchPlaceholderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sort playlists by:.
        /// </summary>
        internal static string PlaylistSortString {
            get {
                return ResourceManager.GetString("PlaylistSortString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Switch to Czech language.
        /// </summary>
        internal static string SwitchLanguageString {
            get {
                return ResourceManager.GetString("SwitchLanguageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Video.
        /// </summary>
        internal static string VideoString {
            get {
                return ResourceManager.GetString("VideoString", resourceCulture);
            }
        }
    }
}
