// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlaylistManager.DAL;

#nullable disable

namespace PlaylistManager.DAL.Migrations
{
    [DbContext(typeof(PlaylistManagerDbContext))]
    [Migration("20250306190038_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("PlaylistManager.DAL.Entities.MultimediaBaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MultimediaBaseEntities");

                    b.HasDiscriminator().HasValue("MultimediaBaseEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.PlaylistBaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playlists");

                    b.HasDiscriminator().HasValue("PlaylistBaseEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.PlaylistMultimediaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MultimediaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MultimediaId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("PlaylistMultimedia");
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.AudioMediaEntity", b =>
                {
                    b.HasBaseType("PlaylistManager.DAL.Entities.MultimediaBaseEntity");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("AudioMediaEntity");
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.VideoMediaEntity", b =>
                {
                    b.HasBaseType("PlaylistManager.DAL.Entities.MultimediaBaseEntity");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Genre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VideoPlaylistEntityId")
                        .HasColumnType("TEXT");

                    b.HasIndex("VideoPlaylistEntityId");

                    b.ToTable("MultimediaBaseEntities", t =>
                        {
                            t.Property("Format")
                                .HasColumnName("VideoMediaEntity_Format");

                            t.Property("Genre")
                                .HasColumnName("VideoMediaEntity_Genre");
                        });

                    b.HasDiscriminator().HasValue("VideoMediaEntity");
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.AudioBookPlaylistEntity", b =>
                {
                    b.HasBaseType("PlaylistManager.DAL.Entities.PlaylistBaseEntity");

                    b.HasDiscriminator().HasValue("AudioBookPlaylistEntity");
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.MusicPlaylistEntity", b =>
                {
                    b.HasBaseType("PlaylistManager.DAL.Entities.PlaylistBaseEntity");

                    b.HasDiscriminator().HasValue("MusicPlaylistEntity");
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.VideoPlaylistEntity", b =>
                {
                    b.HasBaseType("PlaylistManager.DAL.Entities.PlaylistBaseEntity");

                    b.HasDiscriminator().HasValue("VideoPlaylistEntity");
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.AudioBookEntity", b =>
                {
                    b.HasBaseType("PlaylistManager.DAL.Entities.AudioMediaEntity");

                    b.Property<Guid?>("AudioBookPlaylistEntityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Genre")
                        .HasColumnType("INTEGER");

                    b.HasIndex("AudioBookPlaylistEntityId");

                    b.HasDiscriminator().HasValue("AudioBookEntity");
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.MusicEntity", b =>
                {
                    b.HasBaseType("PlaylistManager.DAL.Entities.AudioMediaEntity");

                    b.Property<int>("Genre")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MusicPlaylistEntityId")
                        .HasColumnType("TEXT");

                    b.HasIndex("MusicPlaylistEntityId");

                    b.ToTable("MultimediaBaseEntities", t =>
                        {
                            t.Property("Genre")
                                .HasColumnName("MusicEntity_Genre");
                        });

                    b.HasDiscriminator().HasValue("MusicEntity");
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.PlaylistMultimediaEntity", b =>
                {
                    b.HasOne("PlaylistManager.DAL.Entities.MultimediaBaseEntity", "Multimedia")
                        .WithMany()
                        .HasForeignKey("MultimediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlaylistManager.DAL.Entities.PlaylistBaseEntity", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Multimedia");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.VideoMediaEntity", b =>
                {
                    b.HasOne("PlaylistManager.DAL.Entities.VideoPlaylistEntity", null)
                        .WithMany("Multimedia")
                        .HasForeignKey("VideoPlaylistEntityId");
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.AudioBookEntity", b =>
                {
                    b.HasOne("PlaylistManager.DAL.Entities.AudioBookPlaylistEntity", null)
                        .WithMany("Multimedia")
                        .HasForeignKey("AudioBookPlaylistEntityId");
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.MusicEntity", b =>
                {
                    b.HasOne("PlaylistManager.DAL.Entities.MusicPlaylistEntity", null)
                        .WithMany("Multimedia")
                        .HasForeignKey("MusicPlaylistEntityId");
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.AudioBookPlaylistEntity", b =>
                {
                    b.Navigation("Multimedia");
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.MusicPlaylistEntity", b =>
                {
                    b.Navigation("Multimedia");
                });

            modelBuilder.Entity("PlaylistManager.DAL.Entities.VideoPlaylistEntity", b =>
                {
                    b.Navigation("Multimedia");
                });
#pragma warning restore 612, 618
        }
    }
}
